import { styles } from "./styles";
import { demoScript } from "./demo";

const icon = "https://raw.githubusercontent.com/tubasasakunn/vela/main/Resources/AppIcon.iconset/icon_512x512.png";
const lights = '<span class="traffic" aria-hidden="true"><i></i><i></i><i></i></span>';
const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5"/></svg>';
const download = `<a class="download" href="/download">${arrow}Mac版をダウンロード</a>`;

export const page = `<!doctype html>
<html lang="ja"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vela — Macのいつもの操作を、ひとつのキーで。</title>
<meta name="description" content="アプリを開く、コピー履歴から貼り付ける、ウィンドウを並べる。Velaは毎日のMac操作を好きなショートカットにまとめる無料のmacOSアプリです。">
<meta name="theme-color" content="#fafaff"><link rel="icon" href="${icon}">
<meta property="og:title" content="Vela — Macのいつもの操作を、ひとつのキーで。"><meta property="og:description" content="コピー履歴、アプリ起動、ウィンドウ整理。動くデモで、Velaのできることを試してみてください。"><meta property="og:type" content="website"><meta property="og:image" content="${icon}"><meta property="og:locale" content="ja_JP"><link rel="canonical" href="https://vela.basaapp.com/">
<style>${styles}</style><script defer src="/demo.js?v=20260922-2"></script></head>
<body><a class="skip" href="#main">本文へ移動</a>
<header class="shell header"><a class="brand" href="/" aria-label="Vela ホーム"><img src="${icon}" width="36" height="36" alt="">Vela</a><nav aria-label="メインナビゲーション"><a href="#features">できること</a><a href="#setup">はじめかた</a><a class="nav-download" href="/download">ダウンロード <span aria-hidden="true">↓</span></a></nav></header>
<main id="main">
<section class="hero"><div class="hero-copy shell"><p class="intro"><span class="status-dot"></span>あなたのMacに、小さな近道。</p><h1>Macの「いつもの」を、<br>ひとつのキーで。</h1><p class="lead">アプリを開く。さっきのコピーを貼る。ウィンドウを並べる。<br class="desktop-break">Velaは、毎日の操作を好きなショートカットにまとめるMacアプリです。</p>${download}<p class="requirements">無料で使えます <span>／</span> macOS 14以降・Apple silicon</p></div>
<div class="experience" id="demo"><div class="demo-heading"><span><span class="status-dot"></span>まずは、ここで試してみよう</span><div class="demo-controls"><button id="play-demo" class="text-button" type="button" aria-pressed="false">▶ 自動で見る</button><button id="replay" class="text-button" type="button">↻ 最初から</button></div></div>
<div class="demo-tabs" role="tablist" aria-label="Velaの機能デモ"><button type="button" role="tab" aria-selected="true" aria-controls="demo-panel" id="tab-clipboard" data-mode="clipboard">コピーを取り出す</button><button type="button" role="tab" aria-selected="false" aria-controls="demo-panel" tabindex="-1" id="tab-windows" data-mode="windows">ウィンドウを並べる</button><button type="button" role="tab" aria-selected="false" aria-controls="demo-panel" tabindex="-1" id="tab-launcher" data-mode="launcher">アプリを開く</button></div>
<div class="key-guide"><div class="guide-copy" aria-live="polite"><strong id="guide-title">① このキーで、コピー履歴を開く</strong><p id="guide-help">ControlとShiftを押しながら、数字の7。</p></div><div class="guide-action"><button type="button" id="demo-keys" class="demo-keys" aria-label="Control + Shift + 7：コピー履歴を開く"><kbd>Control</kbd><span>+</span><kbd>Shift</kbd><span>+</span><kbd>7</kbd></button><span>このキー表示をクリック・タップしてもOK</span></div></div>
<div class="desktop" id="demo-panel" role="tabpanel" aria-labelledby="tab-clipboard" data-mode="clipboard" data-step="0" data-open="false">
<div class="desktop-menu" aria-hidden="true"><b>●</b><strong id="menu-app">メモ</strong><span>ファイル</span><span>編集</span><span>表示</span><span class="menu-right">火 10:24</span></div>
<div class="desktop-landscape" aria-hidden="true"><i></i><i></i><i></i></div>
<div class="app-window notes-window"><div class="window-bar">${lights}<span>打ち合わせメモ</span><span class="window-symbol" aria-hidden="true">▤</span></div><div class="note-body"><span class="note-date">今日 10:24</span><h3>次のアイデアを、形に。</h3><p>デザインの打ち合わせ<br>火曜日 14:00から</p><div class="note-divider"></div><p class="note-label">参考にするページ</p><p id="pasted-text" class="pasted-text">ここにリンクを貼り付けたい<span class="caret"></span></p><div class="calendar-demo"><h3>9月の予定</h3><div class="calendar-grid calendar-weekdays"><span>月</span><span>火</span><span>水</span><span>木</span><span>金</span><span>土</span><span>日</span></div><div class="calendar-grid"><span class="">21</span><span class="today">22</span><span class="">23</span><span class="">24</span><span class="">25</span><span class="">26</span><span class="">27</span></div><div class="calendar-event">14:00　デザインの打ち合わせ</div></div><div class="note-lines" aria-hidden="true"><i></i><i></i></div></div></div>
<div class="app-window browser-window" aria-hidden="true"><div class="window-bar">${lights}<span>今週のデザイン</span></div><div class="mini-site"><span>Studio journal</span><h3>Less noise.<br>More room.</h3><div class="mini-art"><i></i></div><p>余白から、新しいアイデアを。</p></div></div>
<div class="vela-palette" id="palette" inert><div class="palette-heading"><img src="${icon}" alt="" width="22" height="22"><span id="palette-title">クリップボード履歴</span><kbd>esc</kbd></div><label class="searchbox"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><input id="demo-search" placeholder="コピーした内容を検索…" aria-label="デモのコピー履歴を検索" autocomplete="off" spellcheck="false"></label><div id="demo-results" class="demo-results"><button class="result selected" data-value="https://studio.example/design" type="button"><span class="result-icon link-icon">↗</span><span><b>https://studio.example/design</b><small>リンク · 2分前</small></span><kbd>↵</kbd></button><button class="result" data-value="火曜日の14時から、よろしくお願いします。" type="button"><span class="result-icon text-icon">Aa</span><span><b>火曜日の14時から、よろしくお願いします。</b><small>テキスト · 5分前</small></span></button><button class="result" data-value="デザインの打ち合わせ" type="button"><span class="result-icon text-icon">Aa</span><span><b>デザインの打ち合わせ</b><small>テキスト · 12分前</small></span></button></div><div class="palette-footer"><span>↑ ↓ 選択</span><span>↵ <span id="palette-action">貼り付け</span></span></div></div>
<div class="demo-toast" id="demo-toast" aria-hidden="true">✓ 貼り付けました</div>
</div>
<div class="demo-caption"><p id="demo-caption" aria-live="polite">コピーし直さなくて大丈夫。履歴のリンクを選んで、メモに貼り付けてみてください。</p><button type="button" class="demo-next" id="demo-next">リンクを貼り付ける <span aria-hidden="true">↵</span></button></div>
<p class="demo-disclaimer">ブラウザで試せる操作イメージです。デモ内だけで動きます。キーはこのデモ用の設定例です。反応しない場合はキー表示をクリックしてください。</p></div>
</section>
<section class="features shell" id="features"><div class="section-heading"><p class="section-kicker">探す時間を、作る時間に。</p><h2>小さな操作ほど、<br>すっと終わらせたい。</h2><p>何度も繰り返すことに、短い道をつくりました。</p></div>
<div class="feature-grid">
<article class="feature"><div class="feature-art clip-art" aria-hidden="true"><div class="clip-stack"><div><span>↗</span> 参考にしていたリンク</div><div><span>Aa</span> ひとつ前にコピーした文章</div><div><span>✓</span> 必要なものを、もう一度。</div></div><span class="art-key">Ctrl ⇧ 7</span></div><h3>「さっきのコピー」が、ここに。</h3><p>上書きしてしまった文章やリンクも履歴から検索。選んで、そのまま作業中のアプリへ貼り付けられます。</p></article>
<article class="feature"><div class="feature-art window-art" aria-hidden="true"><div class="tiny-window one">${lights}<div></div><div></div><div></div></div><div class="tiny-window two">${lights}<div></div><div></div></div><span class="art-key">Ctrl ⇧ 8</span></div><h3>並べる。広げる。切り替える。</h3><p>ウィンドウを左右に整列したり、最大化したり。別のディスプレイへの移動も、キーひとつで。</p></article>
<article class="feature"><div class="feature-art ocr-art" aria-hidden="true"><div class="paper"><span>今日のひとこと</span><strong>ひらめきは、<br>いつもの中に。</strong><div class="selection-frame"></div></div><span class="ocr-chip">✓ テキストをコピー</span></div><h3>選べない文字も、コピーする。</h3><p>画像や画面の中の文字を、範囲で選択。認識したテキストをクリップボードに取り出せます。</p></article>
<article class="feature"><div class="feature-art snippet-art" aria-hidden="true"><div class="snippet-list"><span>返信用の定型文 <b>3</b></span><p>お礼のひとこと <span>↵</span></p><p>日程のご案内</p></div><div class="snippet-bubble">ご連絡ありがとうございます。</div></div><h3>よく書く文章は、呼び出すだけ。</h3><p>挨拶、署名、いつもの返信。定型文をグループでまとめて、必要なときにすぐ呼び出せます。</p></article>
</div></section>
<section class="personal-section" id="setup"><div class="shell personal-grid"><div class="personal-copy"><p class="section-kicker">あなたのやり方に、合わせます。</p><h2>設定は、<br>AIと話しながら。</h2><p>「このキーでメモを開きたい」<br>「ウィンドウは左半分に寄せたい」</p><p>やりたいことを、いつものAIアシスタントに。<br>Velaが用意するガイドを読ませて、<br>自分の使い方に合う設定を作れます。</p><p class="small-copy">設定はMac上のJavaScriptファイルに保存。<br>自分で書き換えることもできます。</p></div><div class="setup-illustration"><div class="chat-question">Control＋Shift＋8 でウィンドウを<br>左半分に並べたい。</div><div class="config-window"><div class="window-bar">${lights}<span>vela.js</span></div><pre><span class="code-comment">// 自分のショートカットをひとつ。</span>
<span class="code-fn">Vela.hotkey</span>(
  <span class="code-string">"control+shift+8"</span>,
  () =&gt; Vela.window(<span class="code-string">"leftHalf"</span>)
);</pre><div class="config-check"><span>✓</span> 設定をチェックしてから反映</div></div><p>キーも、動作も、自分の好きな組み合わせに。</p></div></div>
<div class="shell getting-started"><h3>使いはじめるまでの、3ステップ。</h3><ol><li><span>1</span><div><h4>Velaをダウンロード</h4><p>DMGを開いて、Velaをアプリケーションフォルダへ。</p></div></li><li><span>2</span><div><h4>AIと初期設定</h4><p>Velaを開き、案内に沿ってAIにガイドを渡します。必要な権限もここで許可。</p></div></li><li><span>3</span><div><h4>いつもの操作を、短く</h4><p>使いたい機能とキーを決めて、Macで試してみましょう。</p></div></li></ol><a class="setup-link" href="/setup.md">AIに渡せるセットアップガイドを読む <span aria-hidden="true">↗</span></a></div></section>
<section class="shell faq-section" id="faq"><div><p class="section-kicker">使う前に、知っておきたいこと。</p><h2>よくある質問</h2></div><div class="faq-list"><details><summary>Velaって、どんなアプリ？</summary><p>アプリ起動、クリップボード履歴、定型文、画面の文字認識、ウィンドウ操作をまとめたmacOS用ユーティリティです。それぞれに自分のショートカットを割り当てて使えます。</p></details><details><summary>無料で使えますか？</summary><p>はい。Velaは無料で使えます。Velaのアカウント登録も必要ありません。設定を手伝ってもらうAIアシスタントは、別途ご用意ください。</p></details><details><summary>どのMacで動きますか？</summary><p>配布しているDMGはApple silicon搭載のMac、macOS 14以降に対応しています。Appleの公証を受けたアプリです。機能によって、アクセシビリティ・画面収録などの許可が必要です。</p></details><details><summary>コードが書けなくても使えますか？</summary><p>AIアシスタントに設定作成を手伝ってもらえます。初回起動のガイドから始めて、「何を、どのキーで使いたいか」を伝えてください。Velaは設定を検証してから反映します。</p></details><details><summary>コピーした内容はどこに保存されますか？</summary><p>クリップボード履歴と設定はMac上に保存されます。Velaに利用状況を収集する解析SDKはありません。文脈に合う定型文を選ぶ補助機能では、対応環境でAppleのPrivate Cloud Computeを利用する場合があります。</p></details><details><summary>このページのデモと、実際のアプリは同じですか？</summary><p>デモは機能の流れを分かりやすく再現したものです。Macやクリップボードにはアクセスしません。実際の表示やキーの組み合わせは、Velaのバージョンと設定によって異なります。</p></details></div></section>
<section class="closing shell"><img src="${icon}" alt="" width="72" height="72"><h2>いつものMacが、<br>ちょっと手になじむ。</h2><p>まずは、ひとつのショートカットから。</p>${download}<p class="requirements">無料 · macOS 14以降 · Apple silicon</p></section>
</main><footer class="shell footer"><a class="brand" href="/"><img src="${icon}" width="25" height="25" alt="">Vela</a><span>毎日のMac操作に、小さな近道を。</span><a href="/setup.md">セットアップ</a><a href="#faq">よくある質問</a><small>© 2026 Vela</small></footer>
<noscript><p class="noscript">操作デモにはJavaScriptが必要です。機能の説明とダウンロードはそのままご利用いただけます。</p></noscript></body></html>`;

export { demoScript };
